name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository.name }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s) --tag ${{ env.IMAGE_NAME }}:latest
