name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.event.repository.name }}
  DOCKER_ID: ${{ secrets.DOCKERHUB_ID }}
  DOCKER_PWD: ${{ secrets.DOCKERHUB_PWD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s) --tag ${{ env.IMAGE_NAME }}:latest
    - name: Login Docker hub
      run: docker login -u ${{ env.DOCKER_ID }} -p ${{ env.DOCKER_PWD }}
    - name: Publish to Docker hub
      run: docker push ${{ env.DOCKER_ID }}/${{ env.IMAGE_NAME }}
