name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION: v${{ github.run_number }}

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    # -
    #   name: Docker meta
    #   id: meta
    #   uses: docker/metadata-action@v3
    #   with:
    #     images: thielmann/php-sqlserver-redis-docker
    #     tags: ${{ env.GITHUB_RUN_NUMBER }}
    -
      name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: thielmann/php-sqlserver-redis-docker:${{ env.VERSION }},thielmann/php-sqlserver-redis-docker:latest
        
        
    # - name: Build the Docker image
    #   env:
    #     DOCKER_ID: ${{ secrets.DOCKERHUB_ID }}
    #   run: docker build . --file Dockerfile --tag $DOCKER_ID/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
    # - name: Login Docker hub
    #   env:
    #     DOCKER_ID: ${{ secrets.DOCKERHUB_ID }}
    #     DOCKER_PWD: ${{ secrets.DOCKERHUB_PWD }}
    #   run: docker login -u $DOCKER_ID -p $DOCKER_PWD
    # - name: Publish to Docker hub
    #   env:
    #     DOCKER_ID: ${{ secrets.DOCKERHUB_ID }}
    #   run: docker push $DOCKER_ID/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
