name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_ID: ${{ secrets.DOCKERHUB_ID }}
      run: docker build . --file Dockerfile --tag $DOCKER_ID/${{ env.IMAGE_NAME }}:$(date +%s)
    - name: Login Docker hub
      env:
        DOCKER_ID: ${{ secrets.DOCKERHUB_ID }}
        DOCKER_PWD: ${{ secrets.DOCKERHUB_PWD }}
      run: docker login -u $DOCKER_ID -p $DOCKER_PWD
    - name: Publish to Docker hub
      env:
        DOCKER_ID: ${{ secrets.DOCKERHUB_ID }}
      run: docker push $DOCKER_ID/${{ env.IMAGE_NAME }}
